# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortener.validation


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitUpdatedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shortenurl',
            name='origin_url',
            field=models.CharField(max_length=200, unique=True, validators=[shortener.validation.validate_url, shortener.validation.validate_first_essential_part]),
        ),
        migrations.AddField(
            model_name='information',
            name='shorten_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.ShortenURL'),
        ),
        migrations.AddField(
            model_name='hitupdatedtime',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.Information'),
        ),
    ]
