# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='origin_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
