# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20171130_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitupdatedtime',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_time', to='shortener.Information'),
        ),
    ]
