# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validation


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20171130_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='origin_url',
            field=models.CharField(max_length=200, unique=True, validators=[shortener.validation.validate_url, shortener.validation.validate_first_essential_part]),
        ),
    ]
