# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20171203_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
