# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20171130_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
